### ISSUE TITLE
Parser problems

### ISSUE THREAD

**Issue by stephensrmmartin** [ErwinHaasnoot/QRTEngine#41]
I am currently trying out qrtengine v15 given the current problems with qualtrics' latest update.

The task works well enough for my needs. I decided to run myself through the study and attempt to look at the data.

The parser is erroring out with the following message:

```
[./parser.py:9] Initing parser on file: Confederate_Flag_AMP.csv
[/home/hwkiller/Dropbox/Research/Confederate flag and implicit attitudes/Documents/Materials/QRTengine/Parser/qrteparser-webservice-master/qrte_parser_python/qrtemarkupnode.py:346] [ERROR] [CODE:4][TAG:ERR_COLUMN_INVALID_JSON] Subject: {'ImportId': 'responseId'}, Data: {'ImportId': 'embeddedData-QRTE_columns'}, SubjectId: 1 - Column cache is not valid JSON. Likely that respondent quit the survey early. If this is not the case, please report immediately to support@qrtengine.com, with the survey .qsf and the original data file.
[/home/hwkiller/Dropbox/Research/Confederate flag and implicit attitudes/Documents/Materials/QRTengine/Parser/qrteparser-webservice-master/qrte_parser_python/qrtemarkupnode.py:346] [ERROR] [CODE:4][TAG:ERR_COLUMN_INVALID_JSON] Subject: R_O88vCG0iMA73fdn, Data: , SubjectId: 2 - Column cache is not valid JSON. Likely that respondent quit the survey early. If this is not the case, please report immediately to support@qrtengine.com, with the survey .qsf and the original data file.
Traceback (most recent call last):
  File "./parser.py", line 27, in <module>
    main(*sys.argv[1:])
  File "./parser.py", line 22, in main
    QRTEParser.parse(file, outfile=file.split('.')[0]+'_out.csv',exit_q_unique = False)
  File "/home/hwkiller/Dropbox/Research/Confederate flag and implicit attitudes/Documents/Materials/QRTengine/Parser/qrteparser-webservice-master/qrte_parser_python/qrteparser.py", line 20, in parse
    parser._parse()
  File "/home/hwkiller/Dropbox/Research/Confederate flag and implicit attitudes/Documents/Materials/QRTengine/Parser/qrteparser-webservice-master/qrte_parser_python/qrteparser.py", line 31, in _parse
    node = QRTEMarkUpNode.create(self.file, self.exit_q_unique)
  File "/home/hwkiller/Dropbox/Research/Confederate flag and implicit attitudes/Documents/Materials/QRTengine/Parser/qrteparser-webservice-master/qrte_parser_python/qrtemarkupnode.py", line 213, in create
    headers, blocks, ignore_columns, exit_questions = node.build_block_meta(file, exit_q_unique)
  File "/home/hwkiller/Dropbox/Research/Confederate flag and implicit attitudes/Documents/Materials/QRTengine/Parser/qrteparser-webservice-master/qrte_parser_python/qrtemarkupnode.py", line 349, in build_block_meta
    return headers, blocks, ignore_columns, exit_questions
UnboundLocalError: local variable 'exit_questions' referenced before assignment
```

I also attempted to run the python-django webservice, but the page does not load correctly.
I started the server with: python2 manage.py runserver 127.0.0.1:7557 and connected via firefox, and received:

```

Page not found (404)
Request Method:     GET
Request URL:    http://127.0.0.1:7557/

Using the URLconf defined in qrteparser.urls, Django tried these URL patterns, in this order:

    ^admin/
    ^list/$ [name='list']

The current URL, , didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

**Comment by stephensrmmartin** [comment]
Note, that the output format of qualtrics indeed appears slightly different than I recall from previous studies I have run.

It now has a third row with, e.g., {'ImportId': 'responseId'}
Whereas, I only recall it having 2 header rows previously.

**Comment by ErwinHaasnoot** [comment]
Hi Stephen,

Thanks for reporting this issue. These seem to be the same issues:

https://github.com/ErwinHaasnoot/qrteparser-webservice/issues/2
https://github.com/ErwinHaasnoot/qrteparser-webservice/issues/1

So I hope you don't mind if I close this one and continue correspondence in those tickets!

Best,

Erwin

**Comment by stephensrmmartin** [comment]
Ah yes, I see now. Sorry about that.

Is there anything I can do to help debug? I have light-moderate programming experience.
